title: Shyble
description: Software Engineering Manager · AI Researcher · MSc Data Science
url: https://shyble.github.io
permalink: /blog/:title/
author: Kürşat Kutlu Aydemir
plugins:
  - jekyll-feed
